### ISSUE TITLE
Une version web avec docker

### ISSUE THREAD

**Issue by delta-whiplash** [Seysa/japdl#11]
Bonjour après des heures de téléchargements sur mon pc puis ma vm je me suis demandé si il était possible de passer cette application en serveur web afin de pouvoir gérer les téléchargement depuis par exemple mon NAS synology

**Comment by delta-whiplash** [comment]
PS: si vous m'expliquer comment lancer la version actuel en tant que serveur web je peux concevoir le conteneur docker

**Comment by Seysa** [comment]
Bonjour,

L'application n'est pas paramétrée pour être accessible par le web, ce n'est donc pas possible.
Japdl utilise un paquet npm appelé<a href="https://github.com/japdl/japscandl/">`japscandl`</a>que j'ai aussi développé qui possède des fonctions de téléchargement pour japscan. 
Si vous avez des connaissances en node et en javascript, il est possible de l'utiliser pour développer votre propre serveur web.

La doc n'est malheureusement pas encore faite.

**Comment by delta-whiplash** [comment]
je vais voir dès que j'ai le temps merci
