### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by zineedine2010** [Seysa/japdl#12]
Hey,

I would like to thank you for this software first. I can finally enjoy my mangas offline.

There are still some issues with it and i hope my post will help you :
- Some chapters download a blank image like this one : https://www.japscan.me/manga/two-first-class-stars/
- Some mangas where there are chapters classified by volumes and then the rest of the chapters is not classified by volume, the software stops at the latest volume affected chapters.

Thanks.

**Comment by Seysa** [comment]
Hello, webtoons are for now not downloadable, that's why a blank image is downloaded. Can you give me an example of a manga where the volumes download stops ?

**Comment by zineedine2010** [comment]
Ah ok. For the volume problem, here is an example : https://www.japscan.me/manga/re-monster/

**Comment by Seysa** [comment]
Well the program is working as intended here, since these chapters are not in a volume, it cannot put them in a volume.You can still download them as a single file using the chapter download and specifying a range

**Comment by zineedine2010** [comment]
Not really. When you try to download a chapter after the last volume it tells you the max is the last chapter of the last volume. Try it.

**Comment by Seysa** [comment]
You're right, I'm working on a fix

**Comment by zineedine2010** [comment]
Great, thanks a lot. I'll be waiting for the update.

**Comment by Seysa** [comment]
Hello, the bug should be fixed in version 0.8.3

**Comment by zineedine2010** [comment]
Thanks
