### ISSUE TITLE
Numérotation

### ISSUE THREAD

**Issue by djedjezr7** [Seysa/japdl#13]
Bonjour
excellente application !
Est-il possible de faire la numérotation sur 3 digits.
Sur les liseuses par exemple la lecture ne se fait pas bien. Par exemple cela passe de la page volume-1_1.png à l volume-1_10.png au lieu de la volume-1_2.png
Le problème peut être résolu en numérotant volume-1_001.png
Sur 3 digits se serait super pour monter à 999 pages.

Merci

**Comment by Seysa** [comment]
Bonjour,
Merci!
Oui bien sûr c'est un problème auquel je n'avais pas pensé je vais donc l'intégrer à la prochaine mise à jour

**Comment by djedjezr7** [comment]
Merci. 
En tout cas milles bravo, ton programme marche vraiment bien (en plus d'avoir un interface sympa) !!
C'est d'une simplicité d'utilisation redoutable (en général quand c'est simple d'utilisation le code est souvent compliqué derrière). Donc encore bravo !!!
Si tout pouvait marcher aussi bien et facilement !

**Comment by Seysa** [comment]
Merci beaucoup pour ton retour, je suis content que l'application te plaise

**Comment by Seysa** [comment]
Bonjour, c'est effectif dans la version 0.8.3
