### ISSUE TITLE
CBZ - Padding sur nom de chapitre

### ISSUE THREAD

**Issue by alamoureux** [Seysa/japdl#15]
Bonjour,

Est-il possible, lors du pack en cbz (ou au DL des chapitres), de renommer les index de chapitres avec un padding ?
Ca permettrait aux liseuses de lire correctement les volumes regroupant des chapitres avec différents longueur d'index:

 - 9, 10, 11 -> est lu 10, 11, 9
 - 09, 10, 11 -> sera lu 09, 10, 11

Merci,

**Comment by Seysa** [comment]
Bonjour,

Je suis en train de travailler sur ce changement qui devrait arriver aujourd'hui

**Comment by Seysa** [comment]
C'est disponible dans la version 0.9.0

**Comment by alamoureux** [comment]
Top, merci !
En tout cas, appli très appréciée.
