### ISSUE TITLE
Dossier de sauvegarde reste même si on le change (cf description)

### ISSUE THREAD

**Issue by arnaudgs** [Seysa/japdl#16]
Actuellement : 
Si on ouvre l'application, qu'on change le dossier de sauvegarde et qu'on clique sur "sauvegarder"
Ensuite on lance un téléchargement
Le dossier de téléchargement restera l'ancien dossier, alors que le bouton "ouvrir le dossier" dans "mangas téléchargés" ouvre sur le nouveau dossier

Attendu : 
Le dossier de téléchargement doit être mis à jour partout lors de sa mise à jour.

**Comment by arnaudgs** [comment]
Note : c'est avec la version 0.10.2

**Comment by Seysa** [comment]
Bonjour,

Tout changement des options est effectif au prochain redémarrage pour éviter les problèmes. Je vais ajouter un message l'expliquant dans les options. Un changement à la volé du dossier de téléchargement pendant un téléchargement pourrait avoir des effets indésirables.

**Comment by arnaudgs** [comment]
Normalement étant donné que tu as un framework (vueJs) ce genre de truc ne devrait pas être un problème. Tu n'as pas un store qui permet d'update l'ensemble de tes données ? 
Ce que tu peux faire quand tu lances un DL c'est que ce DL se base sur ses informations qui lui ont été fourni au moment de la création de ton objet de DL (je ne sais pas si tu passes par un objet), mais ça serait plus safe que de te baser à chaque fois sur les infos globales.

Sinon j'ai essayé de faire un npm install sur mon mac et je me suis fait lamentablement jeté hier. 
Je ne devais pas être sur la bonne branche ou alors c'est parce que je suis sous mac (ça me ferai un peu chier quand même que ce soit ça le pb), je vais aller fouiller les logs de npm.

D'ailleurs tu n'as pas de package-lock.json sur ton projet, tu aurais du le laisser. Ca permet de fixer certaines sous dependances

**Comment by Seysa** [comment]
De par l'architecture actuelle, un objet downloader est instancié au lancement du programme, puis il sera réutilisé pour tout téléchargement. Chaque option est donnée en paramètre au constructeur et ne change pas jusqu'à la fin de la vie de l'objet.

Un redémarrage de l'application n'est pas un assez gros obstacle pour refaire l'architecture.

Je n'utilise pas de package-lock.json puisqu'il y a un yarn.lock

**Comment by arnaudgs** [comment]
My bad je suis trop "enterprisey", merci j'avais oublié yarn...

**Comment by arnaudgs** [comment]
Bon très bon travail, ça marche bien sous Mac (juste il faut aller à la main chercher l'éxécutable de chrome)
Si un jour j'ai le temps je te ferai une PR pour que ça marche nickel sous mac (pour la détection de chrome)

**Comment by Seysa** [comment]
Merci, la PR sera la bienvenue
