### ISSUE TITLE
Chapitre de fin non remis a zero

### ISSUE THREAD

**Issue by AnanthTrebuh** [Seysa/japdl#18]
Bonjour, 
Lorsqu'on choisi de télécharger plusieurs chapitre et qu'on a sélectionner un chapitre de fin, la valeur reste enregistrer sauf si on met une nouvelle valeur de fin. 
Cela pose un problème lorsque après on ne veux en prendre qu'un car si la valeur du chapitre de fin est supérieur alors ça télécharge tout les chapitres meme si on ne voulais en prendre qu'un. 
Par contre si la valeur du chapitre de début est supérieur au chapitre de fin encore enregistrer le téléchargement rest à 0% et bloque. on est obligé de fermé et relancer l'application.

**Comment by Seysa** [comment]
Bonsoir,

Il y avait effectivement un problème de ma part que je pense avoir corrigé. La prochaine version devrait contenir ce fix.

Merci du retour

**Comment by Seysa** [comment]
Bonjour, la version 0.13.0 contient ce correctif.
