### ISSUE TITLE
pas d'acces a japscan

### ISSUE THREAD

**Issue by Endymi0n74** [Seysa/japdl#19]
hello, depuis l'application indique japscan inaccessible
est-ce normal ?

**Comment by Seysa** [comment]
Bonjour,

Japscan a changé son système et possède maintenant une sécurité supplémentaire qui filtre pour l'instant les requêtes au serveur de japdl. L'application est donc pour le moment inutilisable, le temps que je trouve une solution.

Trouver une solution peut être long, merci d'être patient

**Comment by Endymi0n74** [comment]
aucun soucis, je faisais sans avant je peux bien vivre sans un moment :)

**Comment by Adel-Chaker** [comment]
Pour mon information la sécurité viens du : Cloudflare? De mon côté j'essaie de faire un équivalent en Dart pour android 4.2 et + (Car j'ai une liseuse sous android qui ne support plus les nouveau Navigateur). Mais avant de me lancer pleinement dedans, je me suis retrouvé en face de ce mur qui me semble infranchissable... pour l'instant

**Comment by Endymi0n74** [comment]
j'ai eu du mal a comprendre la nouvelle version mais ça fonctionne

**Comment by Seysa** [comment]
Bonjour, quelques fonctionnalitées sont effectivement manquantes mais malheureusement c'est comme ça avec leur sécurité qui a augmenté.

**Comment by nimist** [comment]
salut,
chez moi ça ne fonctionne pas, la page chrome s'ouvre et quand je lance la recherche d'un manga pas de connexion à japscan

**Comment by Seysa** [comment]
Alors attention, la recherche comme sur japscan n'existe plus.
Il faut entrer le nom du manga comme dans les liens japscan. Par exemple, pour chercher One Piece, il faut maintenant taper "one-piece" dans la recherche comme indiqué en dessous du champ de la recherche.
La bulle sur la page d'accueil qui indique qu'il n'y a pas de connexion a japscan est fausse pour le moment, il faut essayer malgré sa présence.

**Comment by nimist** [comment]
je fais ça, ensuite ça ouvre la page de japscan du manga voulu, mais ça charge sur la page checking if the site is secure

**Comment by Endymi0n74** [comment]
> je fais ça, ensuite ça ouvre la page de japscan du manga voulu, mais ça charge sur la page checking if the site is secure

en fait comme expliqué il ne faut plus taper one piece mais bien one-piece comme l'indique le nom de la page du manga sur le site

**Comment by nimist** [comment]
C'est ce que je met, avec le -, ex blue-lock. Rien, c'est peut être un problème qui ne vient pas de ton outil, mais de ma config, peut être un problème de dns, ou autre je sais pas

**Comment by Seysa** [comment]
Bonjour, c'est arrivé à plusieurs personnes sur le discord qui ont ( je crois ) trouvé une solution en changeant leur navigateur dans les options. Je n'ai malheureusement pas de solution pour le moment a part d'essayer ça.

Firefox n'est pas compatible comme navigateur de l'application mais chrome, chromium et edge le sont

**Comment by nimist** [comment]
C'est bon, avec edge ça fonctionne
