### ISSUE TITLE
Problème V13

### ISSUE THREAD

**Issue by gaillard03** [Seysa/japdl#20]
bonjour, lorsque je lance l'application, j'ai ce message "chrome est contrôlé par un logiciel de test automatisé" et pareil quand j'utilise edge ou autres. Du coup ma barre de recherche ne trouve rien et ça ne se connecte pas à japscan. Est ce que vous avez une solution ?

Désolé je suis débutant dans le domaine

mais merci beaucoup pour le travail que vous effectuez.

**Comment by nimist** [comment]
salut,
c'est normal que ça te marque ça
ensuite tu suis les instructions, tu tapes le nom du manga comme il est écrit sur le site, exemple pour One Piece : one-piece.
Donc si tu veux savoir comment ça s'écrit, tu ouvres une autre fenêtre avec edge ou chrome, sur le site tu recherches ton manga et tu notes dans japdl, tu cliques sur rechercher et ça va fonctionnait normalement

**Comment by gaillard03** [comment]
![image](https://user-images.githubusercontent.com/124121501/216752496-30d4b2d5-a386-456c-81e9-1cd587a93eff.png)
J'ai pu avancer avec l'explication (mettre un tiret et pas d'espace. Du coup dans téléchargement en cours cela reste bloqué à 0%

**Comment by nimist** [comment]
J'ai eu la même chose hier soir, alors que ça fonctionnait très bien dans la journée

**Comment by gaillard03** [comment]
Du coup est ce qu'il y a une solution ??

**Comment by Seysa** [comment]
Bonsoir, le problème est réglé dans la dernière version
