### ISSUE TITLE
Cloudflare security on chapter or volume

### ISSUE THREAD

**Issue by zineedine2010** [Seysa/japdl#22]
Hello,

Thanks for updating this application frequently. Following the latest update, we are getting the manga right as well as the number of chapters, but when we try to scrape the chapter itself, the page stays stuck on cloudflare challenge.

The chapter page works fine when i open it on a normal chrome tab but not on the tab opened by the app.

**Comment by Endymi0n74** [comment]
même soucis depuis peu  :
www.japscan.me
Checking if the site connection is secure
www.japscan.me needs to review the security of your connection before proceeding.
Ray ID: 797b6fbb08a92a74
Performance & security by [Cloudflare](https://www.cloudflare.com/?utm_source=challenge&utm_campaign=m)

**Comment by Endymi0n74** [comment]
ça refonctionnait pour moi après avoir basculé sur l'exe de chrome

**Comment by Seysa** [comment]
Hello, this issue is fixed in the last version
