### ISSUE TITLE
Ca manque de thread

### ISSUE THREAD

**Issue by wiiznokes** [Seysa/japdl#27]
Merci pour cette app.

C'est dommage de ne pas pouvoir ouvrir plus de page à la fois, ainsi que faire plusieurs volume en même temps. Pour l'instant, c'est plutôt long. Aussi, le fait d'ouvrir la page dans un vrai navigateur n'est pas pratique/optimisé.

**Comment by Seysa** [comment]
Bonjour, le fait de ne pas faire de téléchargements en parallèle est pour ne pas mettre à genoux japscan, et aussi pour éviter le ban IP dû à une activité trop élevée.

Pour le moment, le navigateur est la seule solution
