### ISSUE TITLE
Téléchargement et création de volumes impossible

### ISSUE THREAD

**Issue by neontheboss** [Seysa/japdl#28]
Bonjour.
J'ai voulu utilisé l'appli pour me remettre a jour sur 2/3 mangas mais l'appli ne veut plus créer de volumes et lors du téléchargement des chapitres je remarque que les fichiers ont des formats d'images bizarre (1x1 environ 80octets).
Auriez vous une idée?

**Comment by zineedine2010** [comment]
Apparemment il y a eu un changement sur japscan. Il protège les images avec une url blob si j'ai bien compris. Yaura-t-il une mise à jour?

**Comment by alexandre-philippeau** [comment]
Bonjour, tout d'abord un grand merci @Seysa pour avoir développé japdl ! L'outil m'a permis de récupérer tout One Piece en qualité officielle (comprendre les tomes dans le commerce) ! Malheureusement depuis ce jeudi 07/12 il n'est plus possible de télécharger des chapitres. Je confirme qu'on récupère des fichiers de 80 octets. Une mise à jour permettant de contourner la protection mise en place par Japscan est-elle prévue ? En tout cas encore merci pour le temps passé sur cet outils, c'est vraiment appréciable !

**Comment by Seysa** [comment]
Bonjour, comme vous l'avez constaté, l'application ne fonctionne plus pour le moment.

Je vais essayer de trouver une solution rapidement

**Comment by Endymi0n74** [comment]
je n'avais pas vu ce thread je supprime le mien

**Comment by Seysa** [comment]
Problème résolu dans la version 0.15.0

**Comment by Endymi0n74** [comment]
j'ai plus le message d'erreur en 0.15.0 par contre quand je cherche un manga et le choisi il dit "ce manga n'a pas été trouvé"

**Comment by alexandre-philippeau** [comment]
Bonjour @Seysa et merci beaucoup pour la réactivité dans le traitement du problème ! Malheureusement avec la v 0.15.0 lorsqu'on cherche un manga et qu'on clique sur son nom pour accéder aux chapitres/volumes je confirme qu'on on obtient un message d'erreur "ce manga n'a pas été trouvé" et qu'on est bloqué, impossible de télécharger :( Est-ce un problème à corriger côté applicatif ou est-ce moi/nous qui utilisons mal la nouvelle version ? Il y a peut-être une étape qui nous échappe.

**Comment by Endymi0n74** [comment]
j'suis pas le seul du coup ça me rassure. merci encore @Seysa pour la réactivité

**Comment by Seysa** [comment]
Pouvez-vous me donner un scénario de reproduction de bug? de mon coté, tout fonctionne correctement. Est-ce que le bug est là sur tous les mangas ?

**Comment by Endymi0n74** [comment]
![japdl_qwD6wZZ9gS](https://github.com/japdl/japdl/assets/102302606/24399e2c-656c-446d-a2a3-a5b2d2ed5c88)
![japdl_Ym6qUjlIYT](https://github.com/japdl/japdl/assets/102302606/3cf620f6-5501-4ee5-b513-1136e0803a3d)
je vous fait ça dans 5 min

**Comment by Seysa** [comment]
plus besoin @Endymi0n74 , j'ai trouvé le scénario. L'application fonctionne en mode .zip et pas en install .exe pour le moment

**Comment by Seysa** [comment]
merci tout de même

**Comment by Endymi0n74** [comment]
impeccable avec la version zip 
merci encore @Seysa 
edit : j'ai dis de la merde juste avant. ne fonctionne vraiment que via la version zip

**Comment by Endymi0n74** [comment]
parfait avec la 0.15.1 version exe

**Comment by Seysa** [comment]
parfait je ferme l'issue

**Comment by alexandre-philippeau** [comment]
Merci beaucoup @Seysa, le téléchargement refonctionne avec la 0.15.1 en exe ! Top la réactivité, c'est vraiment appréciable, encore merci !
