### ISSUE TITLE
Impossible de télécharger la dernière page d'un chapitre

### ISSUE THREAD

**Issue by GitWhiv** [Seysa/japdl#31]
Bonjour,

Le téléchargement (mode rapide ou non) se bloque toujours au téléchargement de la dernière page du chapitre.

**Comment by gallyandfogia** [comment]
Bonjour,
En effet j'ai le même souci, plus rien ne s'affiche ds la fenêtre ie/edge et le prgm bloque ensuite.
![Capture d'écran 2023-12-13 135412](https://github.com/japdl/japdl/assets/153737731/8baddff6-dc1b-4b61-8acd-1a4b8aff786a)

**Comment by Rejnos115** [comment]
la même chose m'arrive, toutes les pages se téléchargent sauf la dernière. J'espère qu'il y aura une solution

**Comment by Seysa** [comment]
Bonjour, la version 0.16.1 règle ce problème
