### ISSUE TITLE
Crash sur VM proxmox

### ISSUE THREAD

**Issue by Vercety87** [Seysa/japdl#32]
Bonsoir,

Merci pour cette app.

Par contre impossible de la lancer sur une VM Ubuntu hébergé sur un hyperviseur Proxmox.

J'ai une erreur vis à vis du GPU Virtuel : 

./japdl 
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: /usr/lib/x86_64-linux-gnu/dri/virtio_gpu_drv_video.so init failed
libva error: /usr/lib/x86_64-linux-gnu/dri/virtio_gpu_drv_video.so init failed
libva error: /usr/lib/x86_64-linux-gnu/dri/virtio_gpu_drv_video.so init failed
[9243:1219/214426.964265:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)

![image](https://github.com/japdl/japdl/assets/44375309/bee1bb8e-7b55-4df8-be2b-c14a9d414bef)

**Comment by Seysa** [comment]
Bonjour, malheureusement je ne compte pas rendre l'application compatible avec les VM, celà prendrait beaucoup trop de temps, et de la nature changeante de la protection de japscan, un gros travail de port vers une VM pourrait être rendu inutile
