### ISSUE TITLE
Dernière page publicité

### ISSUE THREAD

**Issue by GitWhiv** [Seysa/japdl#33]
Le problème de blocage du téléchargement est résolu ; par contre la dernère page téléchargée n'est pas la bonne. Il s'agit de la publicité de japscan ;

Voici la dernière page sur le site ;

https://www.japscan.lol/lecture-en-ligne/ariadne-l-empire-celeste/148/20.html

Et la dernière page téléchargée qui est une pub
![0148_020](https://github.com/japdl/japdl/assets/105095884/25e456c7-0ac2-4036-9465-7821e2320e2c)

**Comment by Celestus** [comment]
J'ai le même problème : certains volumes sont téléchargés complètement, d'autres non, et j'ai toujours la publicité au début et la même à la fin.

**Comment by Celestus** [comment]
Par exemple avec Reqiuem Chevalier Vampire, les tomes 1 et 2 sont complètement téléchargés, mais pas les suivants.

**Comment by gallyandfogia** [comment]
Bonjour,
idem avec option "mode rapide" désactivé ou activé.
Bonnes fêtes et merci pour votre travail.

**Comment by Celestus** [comment]
Oui,  gallyandfogia a raison, merci pour votre travail, j'ai jeté un coup d'œil au code et c'est une belle prise de tête : je ne pensais pas que Japscan se prenait autant la tête pour empêcher le téléchargement des images. Ce qui est stupide puisqu'il suffit d'une capture d'écran pour les télécharger quand même.

**Comment by Seysa** [comment]
Bonjour, le problème a été pris en compte et devrait être corrigé dans la version 0.17.0
