### ISSUE TITLE
Blocage à la première page

### ISSUE THREAD

**Issue by Celestus** [Seysa/japdl#34]
Bonjour, merci beaucoup pour ce travail de titan. La dernière version bloque encore à la première page. Apparemment les mecs de Japscan ont encore changé le code de leurs pages. Visiblement ils sont tellement des tarés de la pub et veulent tellement rendre leurs pages intéléchargeables qu'ils vont finir par les rendre tout simplement illisibles (en désactivant les bloqueurs de pub leur site est tout simplement inutilisable). Bon courage pour résoudre le problème. Et bonne année ;)

**Comment by gallyandfogia** [comment]
Bonjour,
Effectivement le problème persiste en ayant essayé le mode rapide désactivé ou activé.
C'est rageant car la version précédente fonctionnait jusqu'à un changement de la part de Japscan.
J'espère que vous ne désesperez pas de trouver une solution.
Joyeuses fetes de fin d'années !

**Comment by GitWhiv** [comment]
Bonjour. Je confirme. Plus aucun téléchargement possible.

**Comment by lunatik36** [comment]
C'est rageant ! On ne peut plus rien télécharger. J'espère qu'il y aura bientôt une mise à jour du logiciel pour contourner cette première page de m****

**Comment by RaniaElFahli** [comment]
Je confirme également, malgré la mise à jour 0.17.1 je n'arrive pas à dépasser la première page, les pubs semblent tout bloquer... J'espère qu'il sera possible de les contourner, merci & bonne année :)

**Comment by donk7413** [comment]
je confirme également, 0.17.1

**Comment by Endymi0n74** [comment]
je viens de tester la 17.1 en zip et en exe. bloquage a la premiere page aussi

**Comment by Seysa** [comment]
Bonjour, j'ai ajouté un système qui permettra de mettre à jour les changements des dev de japscan sans sortir de version, la dernière version 0.18.0 possède ce changement. Cette version fonctionne donc en attendant leurs prochains changements

**Comment by Endymi0n74** [comment]
je viens de recup le zip l'exe s'ouvre pas (win 11)

**Comment by Endymi0n74** [comment]
parfait en version setup, le blocage n'est plus présent 
grand bravo

**Comment by Celestus** [comment]
Ne fonctionne pas en version 18.0 que ce soit en version Setup ou portable (ça ne change strictement rien). Blocage à la première page à cause de la pub (porno)...

**Comment by gallyandfogia** [comment]
Bonjour,
La version fonctionnait encore très bien il y a quelques heures.
Japscan a dû modifier encore quelque chose car blocage à nouveau...
Bon courage !

**Comment by Endymi0n74** [comment]
effectivement ne fonctionne a nouveau plus ici aussi

**Comment by Endymi0n74** [comment]
je vais attendre un tutoriel pour la nouvelle version. j'suis pas sur de comprendre l'option du css et j'bloque page 1 :(

**Comment by Endymi0n74** [comment]
j'ai fini par apprendre a lire et j'suis allé sur discord
merci a la communauté

**Comment by Celestus** [comment]
Ça marchait encore ce matin en version 19. Cet après-midi ça ne fonctionne plus. Ils ont dû mettre à jour leur site pour parer au programme.

**Comment by Endymi0n74** [comment]
> Ça marchait encore ce matin en version 19. Cet après-midi ça ne fonctionne plus. Ils ont dû mettre à jour leur site pour parer au programme.

remettre la reference canvas par defaut et ça marche

**Comment by Celestus** [comment]
> > Ça marchait encore ce matin en version 19. Cet après-midi ça ne fonctionne plus. Ils ont dû mettre à jour leur site pour parer au programme.
> 
> remettre la reference canvas par defaut et ça marche

Je ne sais pas comment on fait ça.

**Comment by Celestus** [comment]
Ah, aujourd'hui c'est pire, ça met carrément "Le chemin vers Chrome n'est pas valide, l'application n'a pas pu se lancer correctement".

**Comment by Seysa** [comment]
Bonjour, on va centraliser tout ça dans l'issue #36, comme expliqué dans cette issue c'est "normal", le programme ne fonctionne plus pour le moment
