### ISSUE TITLE
L'option d'export en cbr exporte en cbz

### ISSUE THREAD

**Issue by Topoetry** [Seysa/japdl#8]
L'option d'export en cbr exporte en cbz avec une extension .cbr.
(Ce qui n'est pas pour me déplaire, le cbz étant plus compatible avec mon ecosysteme, mais étrange, tout de même)

**Comment by Seysa** [comment]
Merci de la remarque! C'est vrai c'est une ancienne erreur que je n'avais pas eu le temps de corriger, les vrais cbr arriveront peut être plus tard
