### ISSUE TITLE
les telechargements sont lent

### ISSUE THREAD

**Issue by delta-whiplash** [Seysa/japdl#9]
C'est sans doute pas si embettant que ça mais les téléchargements me semblent lent pourriez vous amélioré ça lors d'une future mise à jour

**Comment by Seysa** [comment]
Bonjour,

La vitesse de téléchargement dépend de 3 facteurs:
- La vitesse de votre ordinateur
- La vitesse de votre connexion internet
- La vitesse du serveur `japscan` au moment de votre téléchargement

Malheureusement, je ne peux pas contrôler ces facteurs. J'essaie tout de même d'optimiser la partie que je peux accélérer, mais je pense que je ne peux pas vraiment faire mieux.

**Comment by delta-whiplash** [comment]
D'accord je vous remercie pour votre retour je télécharge sur un pc avec un ryzen 9 et une connexion 40mbps.

**Comment by Seysa** [comment]
La lenteur doit donc venir de leur site qui n'est franchement pas très bien optimisé

**Comment by delta-whiplash** [comment]
Je vois donc, désolé du dérangement 😅😅
